## Count of resources by consumer ID

In [ ]:
MATCH (n)
RETURN 
  n.consumer_id AS consumer_id,
  n.resource_type AS resource_type,
  COUNT(*) AS count
ORDER BY 
  n.consumer_id ASC, 
  count DESC

In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("./count_resources_by_consumer_id_v1.csv")

In [7]:
df

,consumer_id,resource_type,count
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Claim,273
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Observation,252
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,MedicationRequest,191
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,DiagnosticReport,124
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Encounter,83
...,...,...,...
86,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,CarePlan,3
87,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Medication,3
88,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,MedicationAdministration,3
89,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Patient,1
90,NaN,NaN,1043

In [8]:
list_resources = ["Condition", "Observation", "Encounter", "MedicationRequest", "Procedure", "DiagnosticReport", "Claim", "ExplanationOfBenefit", "Immunization", "AllergyIntolerance", "CarePlan"]

In [12]:
target_df = df[df["resource_type"].isin(list_resources)].sort_values(["consumer_id", "resource_type"])

In [16]:
pivoted = target_df.pivot(index="consumer_id", columns="resource_type", values="count")
pivoted

resource_type,AllergyIntolerance,CarePlan,Claim,Condition,DiagnosticReport,Encounter,ExplanationOfBenefit,Immunization,MedicationRequest,Observation,Procedure
consumer_id,,,,,,,,,,,
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625,3.0,8.0,273.0,63.0,124.0,83.0,82.0,12.0,191.0,252.0,63.0
Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58,9.0,2.0,37.0,15.0,33.0,31.0,37.0,35.0,6.0,233.0,18.0
Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9153d023d,NaN,4.0,51.0,28.0,55.0,35.0,35.0,10.0,16.0,132.0,34.0
Gonzalo160_Duenas839_ed70a28f-30b2-acb7-658a-8b340dadd685,NaN,5.0,134.0,51.0,155.0,59.0,136.0,1.0,75.0,829.0,110.0
Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32,NaN,3.0,103.0,69.0,243.0,56.0,103.0,15.0,47.0,1488.0,217.0
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-85685b6ac939,NaN,3.0,30.0,28.0,104.0,19.0,19.0,16.0,11.0,705.0,92.0

In [20]:
pivoted[["Condition", "Observation", "Encounter", "MedicationRequest", "Procedure", "DiagnosticReport", "Claim", "ExplanationOfBenefit"]]

resource_type,Condition,Observation,Encounter,MedicationRequest,Procedure,DiagnosticReport,Claim,ExplanationOfBenefit
consumer_id,,,,,,,,
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625,63.0,252.0,83.0,191.0,63.0,124.0,273.0,82.0
Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58,15.0,233.0,31.0,6.0,18.0,33.0,37.0,37.0
Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9153d023d,28.0,132.0,35.0,16.0,34.0,55.0,51.0,35.0
Gonzalo160_Duenas839_ed70a28f-30b2-acb7-658a-8b340dadd685,51.0,829.0,59.0,75.0,110.0,155.0,134.0,136.0
Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32,69.0,1488.0,56.0,47.0,217.0,243.0,103.0,103.0
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-85685b6ac939,28.0,705.0,19.0,11.0,92.0,104.0,30.0,19.0

In [21]:
pivoted[["Condition", "Observation", "Encounter", "MedicationRequest", "Procedure", "DiagnosticReport", "Claim", "ExplanationOfBenefit"]].to_dict()

{'Condition': {'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625': 63.0,
  'Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58': 15.0,
  'Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9153d023d': 28.0,
  'Gonzalo160_Duenas839_ed70a28f-30b2-acb7-658a-8b340dadd685': 51.0,
  'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32': 69.0,
  'Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-85685b6ac939': 28.0},
 'Observation': {'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625': 252.0,
  'Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58': 233.0,
  'Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9153d023d': 132.0,
  'Gonzalo160_Duenas839_ed70a28f-30b2-acb7-658a-8b340dadd685': 829.0,
  'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32': 1488.0,
  'Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-85685b6ac939': 705.0},
 'Encounter': {'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625': 83.0,
  'Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58': 31.0,
  'Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9153d023d': 35.0,
  'Gonzalo160_Duenas839_ed70a28f-30b2-acb7-658a-8b340dadd685': 59.0,
  'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32': 56.0,
  'Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-85685b6ac939': 19.0},
 'MedicationRequest': {'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625': 191.0,
  'Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58': 6.0,
  'Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9153d023d': 16.0,
  'Gonzalo160_Duenas839_ed70a28f-30b2-acb7-658a-8b340dadd685': 75.0,
  'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32': 47.0,
  'Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-85685b6ac939': 11.0},
 'Procedure': {'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625': 63.0,
  'Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58': 18.0,
  'Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9153d023d': 34.0,
  'Gonzalo160_Duenas839_ed70a28f-30b2-acb7-658a-8b340dadd685': 110.0,
  'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32': 217.0,
  'Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-85685b6ac939': 92.0},
 'DiagnosticReport': {'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625': 124.0,
  'Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58': 33.0,
  'Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9153d023d': 55.0,
  'Gonzalo160_Duenas839_ed70a28f-30b2-acb7-658a-8b340dadd685': 155.0,
  'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32': 243.0,
  'Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-85685b6ac939': 104.0},
 'Claim': {'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625': 273.0,
  'Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58': 37.0,
  'Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9153d023d': 51.0,
  'Gonzalo160_Duenas839_ed70a28f-30b2-acb7-658a-8b340dadd685': 134.0,
  'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32': 103.0,
  'Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-85685b6ac939': 30.0},
 'ExplanationOfBenefit': {'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625': 82.0,
  'Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58': 37.0,
  'Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9153d023d': 35.0,
  'Gonzalo160_Duenas839_ed70a28f-30b2-acb7-658a-8b340dadd685': 136.0,
  'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32': 103.0,
  'Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-85685b6ac939': 19.0}}